
const VITE_HOST_URL = String(import.meta.env.VITE_HOST_URL)
const VITE_SERVER_SOCKET_HOST_URL = String(import.meta.env.VITE_SERVER_SOCKET_HOST_URL)

const STRICKTMODE = false;
const IMAGE_POST_MAX_FILES = 3;
const IMAGE_ALLOWED_TYPES = ['image/jpeg', 'image/png'];
const VIDEO_POST_MAX_FILES = 1;
const VIDEO_ALLOWED_TYPES = ['audio/mpeg'];

import { TEAM } from "./team";
import ANIMATED_3D_404_NOT_FOUND_PAGE_ERROR_V1 from "../assets/StatusCodeGifs/animated-3D-404-not-found-page-error.gif"
import ANIMATED_CHARACTER_AT_THE_DESK_FOR_UNDER_MAINTENANCE_ERROR_PAGE_v1 from "../assets/StatusCodeGifs/animated-character-at-the-desk-for-under-maintenance-error-page.gif"
import ANIMATED_TURTLE_IN_TROUBL_ERROR_PAGE_V1 from "../assets/StatusCodeGifs/animated-turtle-in-trouble-error-page.gif"
import ELECTROCUTED_CAVEMAN_ANIMATION_404_ERROR_PAGE_V2 from "../assets/StatusCodeGifs/electrocuted-caveman-animation-404-error-page.gif"
import MARIO_GAME_ANIMATION_404_ERROR_PAGE_V3 from "../assets/StatusCodeGifs/mario-game-animation-404--error-page.gif"
import SERVER_ON_FIRE_ERROR_PAGE_ANIMATION_V1 from "../assets/StatusCodeGifs/server-on-fire-error-page-animation.gif"
import SHORT_CIRCUIT_ANIMATED_500_ERROR_PAGE_V1 from "../assets/StatusCodeGifs/short-circuit-animated-500-error-page.gif"
export const ChatEventEnum = Object.freeze({
  // ? once user is ready to go
  CONNECTED_EVENT: "connected",
  // ? when user gets disconnected
  DISCONNECT_EVENT: "disconnect",
  // ? when user joins a socket room
  JOIN_CHAT_EVENT: "joinChat",
  // ? when participant gets removed from group, chat gets deleted or leaves a group
  LEAVE_CHAT_EVENT: "leaveChat",
  // ? when admin updates a group name
  UPDATE_GROUP_NAME_EVENT: "updateGroupName",
  // ? when new message is received
  MESSAGE_RECEIVED_EVENT: "messageReceived",
  // ? when there is new one on one chat, new group chat or user gets added in the group
  NEW_CHAT_EVENT: "newChat",
  // ? when there is an error in socket
  SOCKET_ERROR_EVENT: "socketError",
  // ? when participant stops typing
  STOP_TYPING_EVENT: "stopTyping",
  // ? when participant starts typing
  TYPING_EVENT: "typing",
  // ? when message is deleted
  MESSAGE_DELETE_EVENT: "messageDeleted",
});
export const AvailableChatEvents = Object.values(ChatEventEnum);
const MESSANGER_THEME_ENUM = Object.freeze({
  STATE: ["bg-state-50", "bg-state-100", "bg-state-200", "bg-state-300", "bg-state-400", "bg-state-500", "bg-state-600", "bg-state-700", "bg-state-800", "bg-state-900", "bg-state-950"],
  GRAY: ["bg-gray-50", "bg-gray-100", "bg-gray-200", "bg-gray-300", "bg-gray-400", "bg-gray-500", "bg-gray-600", "bg-gray-700", "bg-gray-800", "bg-gray-900", "bg-gray-950"],
  ZINC: ["bg-zinc-50", "bg-zinc-100", "bg-zinc-200", "bg-zinc-300", "bg-zinc-400", "bg-zinc-500", "bg-zinc-600", "bg-zinc-700", "bg-zinc-800", "bg-zinc-900", "bg-zinc-950"],
  NEUTRAL: ["bg-neutral-50", "bg-neutral-100", "bg-neutral-200", "bg-neutral-300", "bg-neutral-400", "bg-neutral-500", "bg-neutral-600", "bg-neutral-700", "bg-neutral-800", "bg-neutral-900", "bg-neutral-950"],
  STONE: ["bg-stone-50", "bg-stone-100", "bg-stone-200", "bg-stone-300", "bg-stone-400", "bg-stone-500", "bg-stone-600", "bg-stone-700", "bg-stone-800", "bg-stone-900", "bg-stone-950"],
  RED: ["bg-red-50", "bg-red-100", "bg-red-200", "bg-red-300", "bg-red-400", "bg-red-500", "bg-red-600", "bg-red-700", "bg-red-800", "bg-red-900", "bg-red-950"],
  ORANGE: ["bg-orange-50", "bg-orange-100", "bg-orange-200", "bg-orange-300", "bg-orange-400", "bg-orange-500", "bg-orange-600", "bg-orange-700", "bg-orange-800", "bg-orange-900", "bg-orange-950"],
  AMBER: ["bg-amber-50", "bg-amber-100", "bg-amber-200", "bg-amber-300", "bg-amber-400", "bg-amber-500", "bg-amber-600", "bg-amber-700", "bg-amber-800", "bg-amber-900", "bg-amber-950"],
  YELLOW: ["bg-yellow-50", "bg-yellow-100", "bg-yellow-200", "bg-yellow-300", "bg-yellow-400", "bg-yellow-500", "bg-yellow-600", "bg-yellow-700", "bg-yellow-800", "bg-yellow-900", "bg-yellow-950"],
  LIME: ["bg-lime-50", "bg-lime-100", "bg-lime-200", "bg-lime-300", "bg-lime-400", "bg-lime-500", "bg-lime-600", "bg-lime-700", "bg-lime-800", "bg-lime-900", "bg-lime-950"],
  GREEN: ["bg-green-50", "bg-green-100", "bg-green-200", "bg-green-300", "bg-green-400", "bg-green-500", "bg-green-600", "bg-green-700", "bg-green-800", "bg-green-900", "bg-green-950"],
  EMERALD: ["bg-emerald-50", "bg-emerald-100", "bg-emerald-200", "bg-emerald-300", "bg-emerald-400", "bg-emerald-500", "bg-emerald-600", "bg-emerald-700", "bg-emerald-800", "bg-emerald-900", "bg-emerald-950"],
  TEAL: ["bg-teal-50", "bg-teal-100", "bg-teal-200", "bg-teal-300", "bg-teal-400", "bg-teal-500", "bg-teal-600", "bg-teal-700", "bg-teal-800", "bg-teal-900", "bg-teal-950"],
  CYAN: ["bg-cyan-50", "bg-cyan-100", "bg-cyan-200", "bg-cyan-300", "bg-cyan-400", "bg-cyan-500", "bg-cyan-600", "bg-cyan-700", "bg-cyan-800", "bg-cyan-900", "bg-cyan-950"],
  SKY: ["bg-sky-50", "bg-sky-100", "bg-sky-200", "bg-sky-300", "bg-sky-400", "bg-sky-500", "bg-sky-600", "bg-sky-700", "bg-sky-800", "bg-sky-900", "bg-sky-950", "bg-sky-"],
  BLUE: ["bg-blue-50", "bg-blue-100", "bg-blue-200", "bg-blue-300", "bg-blue-400", "bg-blue-500", "bg-blue-600", "bg-blue-700", "bg-blue-800", "bg-blue-900", "bg-blue-950"],
  INDIGO: ["bg-indigo-50", "bg-indigo-100", "bg-indigo-200", "bg-indigo-300", "bg-indigo-400", "bg-indigo-500", "bg-indigo-600", "bg-indigo-700", "bg-indigo-800", "bg-indigo-900", "bg-indigo-950"],
  VIOLET: ["bg-violet-50", "bg-violet-100", "bg-violet-200", "bg-violet-300", "bg-violet-400", "bg-violet-500", "bg-violet-600", "bg-violet-700", "bg-violet-800", "bg-violet-900", "bg-violet-950"],
  PURPLE: ["bg-purple-50", "bg-purple-100", "bg-purple-200", "bg-purple-300", "bg-purple-400", "bg-purple-500", "bg-purple-600", "bg-purple-700", "bg-purple-800", "bg-purple-900", "bg-purple-950"],
  FUCHSIA: ["bg-fuchsia-50", "bg-fuchsia-100", "bg-fuchsia-200", "bg-fuchsia-300", "bg-fuchsia-400", "bg-fuchsia-500", "bg-fuchsia-600", "bg-fuchsia-700", "bg-fuchsia-800", "bg-fuchsia-900", "bg-fuchsia-950"],
  PINK: ["bg-pink-50", "bg-pink-100", "bg-pink-200", "bg-pink-300", "bg-pink-400", "bg-pink-500", "bg-pink-600", "bg-pink-700", "bg-pink-800", "bg-pink-900", "bg-pink-950"],
  ROSE: ["bg-rose-50", "bg-rose-100", "bg-rose-200", "bg-rose-300", "bg-rose-400", "bg-rose-500", "bg-rose-600", "bg-rose-700", "bg-rose-800", "bg-rose-900", "bg-rose-950"],
})
const MESSANGER_THEME_VALUES = Object.values(MESSANGER_THEME_ENUM)
const MESSANGER_THEME_KEYS = Object.keys(MESSANGER_THEME_ENUM)


const AUDIO_LIBRARY_THEME =
  [
    "bg-state-400",
    "bg-gray-400",
    "bg-zinc-400",
    "bg-neutral-400",
    "bg-stone-400",
    "bg-red-400",
    "bg-orange-400",
    "bg-amber-400",
    "bg-yellow-400",
    "bg-lime-400",
    "bg-green-400",
    "bg-emerald-400",
    "bg-teal-400",
    "bg-cyan-400",
    "bg-sky-400",
    "bg-blue-400",
    "bg-indigo-400",
    "bg-violet-400",
    "bg-purple-400",
    "bg-fuchsia-400",
    "bg-pink-400",
    "bg-rose-4000"
  ]

const PROFILE_DUMMY_IMAGE_URL = "https://res.cloudinary.com/db3pdtxym/image/upload/v1716473340/in3fbtrbipkz9glmtui0.webp"
const TAGLIST = [
  // General
  "announcement",
  "update",
  "news",

  // Personal
  "life",
  "family",
  "friends",
  "selfie",
  "travel",
  "vacation",
  "food",
  "health",
  "fitness",
  "motivation",

  // Entertainment
  "music",
  "movies",
  "tv",
  "books",
  "gaming",
  "sports",

  // Technology
  "tech",
  "gadgets",
  "programming",
  "coding",
  "software",
  "hardware",

  // Education
  "learning",
  "school",
  "college",
  "university",
  "onlineCourse",

  // Work
  "career",
  "job",
  "business",
  "entrepreneur",
  "startup",

  // Hobbies
  "art",
  "photography",
  "crafts",
  "cooking",
  "gardening",
  "music",

  // Social Causes
  "charity",
  "volunteering",
  "environment",
  "activism",

  // Miscellaneous
  "funny",
  "memes",
  "quotes",
  "inspiration",
  "events",
  "celebration"
];

export {
  AUDIO_LIBRARY_THEME,
  TEAM,
  MESSANGER_THEME_ENUM,
  MESSANGER_THEME_VALUES,
  MESSANGER_THEME_KEYS,
  VITE_HOST_URL,
  VITE_SERVER_SOCKET_HOST_URL,
  ANIMATED_3D_404_NOT_FOUND_PAGE_ERROR_V1,
  ANIMATED_CHARACTER_AT_THE_DESK_FOR_UNDER_MAINTENANCE_ERROR_PAGE_v1,
  ANIMATED_TURTLE_IN_TROUBL_ERROR_PAGE_V1,
  ELECTROCUTED_CAVEMAN_ANIMATION_404_ERROR_PAGE_V2,
  MARIO_GAME_ANIMATION_404_ERROR_PAGE_V3,
  SERVER_ON_FIRE_ERROR_PAGE_ANIMATION_V1,
  SHORT_CIRCUIT_ANIMATED_500_ERROR_PAGE_V1,
  STRICKTMODE,
  TAGLIST,
  IMAGE_POST_MAX_FILES,
  IMAGE_ALLOWED_TYPES,
  VIDEO_POST_MAX_FILES,
  VIDEO_ALLOWED_TYPES,
  PROFILE_DUMMY_IMAGE_URL
}

export const ANO_GROP_TOPICS =
  [
    "Travel Enthusiasts",
    "Cooking and Recipes",
    "Fitness and Wellness",
    "Book Club",
    "Photography Lovers",
    "Tech Talk",
    "Art and Creativity",
    "Music Makers",
    "Movie Buffs",
    "DIY Projects",
    "Pet Lovers",
    "Gaming Community",
    "Outdoor Adventures",
    "Meditation and Mindfulness",
    "Language Exchange",
    "Career Development",
    "Fashion Trends",
    "Foodies Unite",
    "Parenting Support",
    "Environmental Conservation",
    "Financial Planning",
    "Sports Fans",
    "Local Events and Meetups",
    "Academic Discussions",
    "Political Debates",
    "Health and Nutrition",
    "Yoga and Meditation",
    "Coding and Programming",
    "Mental Health Support",
    "Sustainable Living",
    "Entrepreneurship",
    "Film Making",
    "Car Enthusiasts",
    "Gardening Tips",
    "Philosophy and Ethics",
    "Virtual Reality (VR) Enthusiasts",
    "Cosplay Community",
    "Music Production",
    "History Buffs",
    "Cryptocurrency and Blockchain",
    "DIY Home Decor",
    "Parenting Advice",
    "Travel Hacks",
    "Astronomy and Space Exploration",
    "Writing Workshops",
    "LGBTQ+ Support",
    "Community Service and Volunteering",
    "Meditation and Spirituality",
    "Fitness Challenges",
    "Local Business Networking",
    "Comedy Club",
    "Self-Improvement",
    "Interior Design Inspiration",
    "Wildlife Conservation",
    "Creative Writing",
    "Podcast Discussions",
    "Meditation Techniques",
    "Urban Exploration",
    "Current Events Analysis",
    "Relationship Advice",
    "Craft Beer Enthusiasts",
    "Street Photography",
    "Renewable Energy Solutions",
    "Movie Night Suggestions",
    "Language Learning Groups",
    "Stock Market Discussions",
    "Hiking Trails Exploration",
    "Urban Gardening",
    "Social Justice Advocacy",
    "Poetry Readings",
    "Meditation Retreat Planning",
    "DIY Electronics Projects",
    "Classic Literature Appreciation",
    "Board Games Enthusiasts",
    "Sustainable Fashion Ideas",
    "Virtual Fitness Classes",
    "Cryptocurrency Trading Tips",
    "Cooking Challenges",
    "Art Therapy Sessions",
    "Music Theory Workshops",
    "Historical Reenactments",
    "Travel Photography Tips",
    "Vegan and Vegetarian Cooking",
    "Entrepreneurial Networking",
    "Independent Film Screenings",
    "Mindful Eating Practices",
    "DIY Beauty Products",
    "Vintage Car Restorations",
    "Political Activism",
    "Nature Sketching Workshops",
    "Mindfulness in Daily Life",
    "Adventure Travel Planning",
    "Local History Tours",
    "Robotics Projects",
    "Social Media Marketing Strategies",
    "Slow Fashion Movement",
    "Sustainable Agriculture Practices",
    "DIY Upcycling Projects",
    "LGBTQ+ Film Discussions",
    "Networking for Remote Workers",
    "Film Photography Enthusiasts",
    "AI and Machine Learning Discussions",
    "Home Brewing Techniques",
    "Nature Conservation Initiatives",
    "Writing Poetry Workshops",
    "Science Fiction Book Club",
    "Traveling with Pets Tips",
    "Digital Marketing Strategies",
    "Mountain Biking Adventures",
    "Creative Writing Prompts",
    "DIY Woodworking Projects",
    "Local Art Exhibitions",
    "Renewable Energy Technologies",
    "Cooking for Beginners",
    "Language Exchange for Advanced Speakers",
    "Stock Trading Strategies",
    "Birdwatching Expeditions",
    "Urban Farming Community",
    "Racial Justice Advocacy",
    "Spoken Word Poetry Nights",
    "Group Fitness Challenges",
    "Virtual Reality Game Development",
    "Ethical Fashion Trends",
    "Virtual Music Jam Sessions",
    "World History Discussions",
    "Vegan and Vegetarian Recipes Exchange",
    "Startup Pitch Competitions",
    "Independent Music Releases Showcase",
    "Mindfulness in Education",
    "Backpacking Adventures Planning",
    "Architectural Photography",
    "Sustainable Transportation Solutions",
    "Culinary Adventures",
    "Online Learning Resources Sharing",
    "Street Art Tours",
    "Environmental Policy Debates",
    "Yoga Retreat Planning",
    "Open Source Software Development",
    "Alternative Energy Sources Exploration",
    "DIY Clothing Alterations",
    "LGBTQ+ Rights Activism",
    "Wildlife Photography Tips",
    "Personal Finance Management",
    "Trail Running Community",
    "Science Fiction Film Screenings",
    "Virtual Reality Art Exhibitions",
    "Conscious Consumerism Discussions",
    "Online Fitness Coaching",
    "Cryptocurrency Investment Strategies",
    "Baking and Pastry Making Workshops",
    "DIY Natural Beauty Products",
    "Vintage Motorcycle Restoration",
    "Community Gardening Projects",
    "Diversity and Inclusion in the Workplace",
    "Virtual Music Production Workshops",
    "World Religions Discussions",
    "Plant-Based Nutrition Education",
    "Social Entrepreneurship Ventures",
    "Online Gaming Tournaments",
    "Environmental Education Programs",
    "DIY Home Renovation Projects",
    "LGBTQ+ Literature Discussions",
    "Wildlife Conservation Volunteering",
    "Personal Growth Book Club",
    "Remote Work Productivity Tips",
    "Astrophotography Techniques",
    "Minimalist Lifestyle Discussions",
    "Urban Cycling Advocacy",
    "Sustainable Tourism Initiatives",
    "Handmade Craft Exchanges",
    "Human Rights Advocacy",
    "Science Communication Workshops",
    "Mindful Parenting Support",
    "Adventure Travel Photography",
    "Online Music Production Collaborations",
    "Classical Music Appreciation",
    "Historical Fiction Book Club",
    "Zero Waste Living Tips",
    "Social Impact Investment Opportunities",
    "DIY Green Energy Projects",
    "LGBTQ+ Film Screenings",
    "Community Supported Agriculture (CSA)",
    "Personal Development Seminars",
    "Urban Birdwatching",
    "Virtual Reality Travel Experiences",
    "Eco-Friendly Fashion Swaps",
    "Virtual Reality Gaming Community",
    "Indigenous Rights Activism",
    "Sustainable Architecture Design",
    "DIY Home Brewing Techniques",
    "LGBTQ+ History Discussions",
    "Wildlife Habitat Restoration Projects",
    "Mindfulness Meditation for Beginners",
    "Backpacking Gear Reviews",
    "Environmental Justice Advocacy",
    "Digital Nomad Lifestyle Tips",
    "DIY Herbal Remedies",
    "Classic Car Restoration Tips",
    "Community Clean-up Events",
    "LGBTQ+ Parenting Support",
    "Wilderness Survival Skills",
    "DIY Sustainable Living Solutions",
    "Women in Tech Networking",
    "Sustainable Fishing Practices",
    "Online Language Teaching Methods",
    "Urban Foraging Expeditions",
    "Climate Change Policy Discussions",
    "Sustainable Fashion Brands Showcase",
    "Virtual Reality Storytelling Workshops",
    "LGBTQ+ Poetry Readings",
    "Community Supported Fisheries (CSF)",
    "Personal Finance Workshops",
    "Trail Running Gear Recommendations",
    "Science Fiction Writing Workshops",
    "Urban Agriculture Projects",
    "DIY Home Energy Efficiency Upgrades",
    "LGBTQ+ Art Exhibitions",
    "Wildlife Conservation Research",
    "Mindful Eating Recipes Exchange",
    "Adventure Travel Photography Tips",
    "Virtual Reality Music Festivals",
    "Indigenous Language Revitalization",
    "Sustainable Transportation Advocacy",
    "DIY Natural Cleaning",
  ]